### ISSUE TITLE
1. Cannot display chinese/japanese characters (haven't tried other unicodes) probably. 2. How to paste ? 3. unknown input key for "Shift" etc. 4. unknown redraw event for popmenu etc.

### ISSUE THREAD

**Issue by alexlai97** [vhakulinen/gnvim#27]
1. having trouble displaying unicode

![screenshot-2019-04-20@20 16 49](https://user-images.githubusercontent.com/17771269/56463807-682e5300-63a9-11e9-9748-a4cce74b1dab.png)

As shown above, the left is Gnvim, right is nvim in terminal. Notice that the cursor in both pictures should be on same character but Gnvim seems to have cursor on 12 characters before. 

Notice if I put cursor to the end of line, Gnvim's cursor is on whitespace.
![screenshot-2019-04-20@20 19 21](https://user-images.githubusercontent.com/17771269/56463826-b6435680-63a9-11e9-9435-6433c172417f.png)

And characters from a page (e.g. startify) before was not be cleared
![screenshot-2019-04-20@20 48 56](https://user-images.githubusercontent.com/17771269/56464008-d543e780-63ad-11e9-8139-74d584f5b340.png)

2. how to paste from clipboard?
I tried Ctrl+v, Ctrl+Shift+v, but only showing '^'.

3. whenever I press keystroke other than "0-9a-z", e.g., Shift, Alt, Win, F1, 
Shift and Alt key seems working, but F1-F8 doen't work (help page not showing), 
stdout shows 
![screenshot-2019-04-20@20 30 51](https://user-images.githubusercontent.com/17771269/56463881-52219200-63ab-11e9-9951-d2e307f96d5b.png)

4. whenever I call command or it calls deoplete (whenever a window needs to be drawn)
command
![screenshot-2019-04-20@20 35 19](https://user-images.githubusercontent.com/17771269/56463915-1b984700-63ac-11e9-8638-36d3e13d7d41.png)

deoplete
![screenshot-2019-04-20@20 36 19](https://user-images.githubusercontent.com/17771269/56463918-26eb7280-63ac-11e9-8f48-ac7e2873259a.png)

things seems to work but stdout shows
![screenshot-2019-04-20@20 38 52](https://user-images.githubusercontent.com/17771269/56463936-5601e400-63ac-11e9-9572-1b5cca5fef54.png)

5. snippet not showing where it is from, only showing when I Ctrl+n to it
![screenshot-2019-04-20@20 53 09](https://user-images.githubusercontent.com/17771269/56464039-6450ff80-63ae-11e9-8fa5-ef1b727ece2a.png)

After Ctrl+n 
![screenshot-2019-04-20@21 01 06](https://user-images.githubusercontent.com/17771269/56464067-6f585f80-63af-11e9-8950-4cbece6c5ce1.png)

I am using neosnippet, and it will show [ns] indicating it can be spanned. But in Gnvim, I can trigger the snippet but it is not showing me whether it can be spanned. 

6. does it support previewing feature for [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) other than vim-lsp

Currently it's like this
![screenshot-2019-04-20@21 03 30](https://user-images.githubusercontent.com/17771269/56464088-c8c08e80-63af-11e9-8fda-016d561b1543.png)

**Comment by vhakulinen** [comment]
1. My guess is that this is something to do with double-width characters, but I might be wrong. I have a idea how to fix this; can you give me some piece of text that reproduces the problem you're describing?
2. There isn't any clipboard support built in to gnvim. You'll have to use nvim registers, at least for now.
3. "Failed to turn input...." isn't something you need to worry about. They are there for debugging purposes. I should probably turn those off.
4. I don't understand what the problem here is. Unknown redraw event messages are printed to stdout when gnvim receives a redraw event it doesn't recognize (e.g. aren't implemented nor silenced).
5. That information on the completion menu is (currently) only shown on the selected item (its the `menu` part of the completion item).
6. The `hover` support for `vim-lsp` is implemented by https://github.com/vhakulinen/gnvim-lsp, but similar support for `LanguageClient-neovim` should be trivial to implement. See  `:h gnvim-cursor-tooltip` and related functions.

**Comment by badosu** [comment]
> There isn't any clipboard support built in to gnvim. You'll have to use nvim registers, at least for now.

Just for additional context, you can use (in normal mode) `"+p` to paste from the regular clipboard (ctrl+c) and `*+p` to past from the selection clipboard (text you have previously selected with the mouse)

**Comment by alexlai97** [comment]
>  1. My guess is that this is something to do with double-width characters, but I might be wrong. I have a idea how to fix this; can you give me some piece of text that reproduces the problem you're describing?

The string was "可不可以显示长句子？中文、日本語を勉強しています。"

> 3. "Failed to turn input...." isn't something you need to worry about. They are there for debugging purposes. I should probably turn those off.

But "F1" in terminal nvim will show help page, while in gnvim there is no response. I also have keybindings for F3, F8, neither shows response in gnvim.

> 4. I don't understand what the problem here is. Unknown redraw event messages are printed to stdout when gnvim receives a redraw event it doesn't recognize (e.g. aren't implemented nor silenced).

When I press shift+semicolon, it will show the a window with ":" in it. At the same time, stdout prints unknown redraw event, which confuses me. But nothing breaks and things work as expected.

> 5. That information on the completion menu is (currently) only shown on the selected item (its the `menu` part of the completion item).

Is it possible to toggle to show that information for not selected items ?

**Comment by vhakulinen** [comment]
@alexlai97 can you try if #36 fixes the issue with text rendering you are experiencing?

**Comment by badosu** [comment]
@alexlai97 You can remap C-C, C-V on vim:

```viml
vnoremap <C-C> "+y
map <C-V>       "+gP
cmap <C-V>      <C-R>+
```

See https://superuser.com/questions/61226/configure-vim-for-copy-and-paste-keyboard-shortcuts-from-system-buffer-in-ubuntu

**Comment by alexlai97** [comment]
> @alexlai97 can you try if #36 fixes the issue with text rendering you are experiencing?

After I `make; sudo make install`. It panics. Enabling rust_backtrace=1 gives me 
[err.log](https://github.com/vhakulinen/gnvim/files/3125767/err.log)

**Comment by vhakulinen** [comment]
Run with `cargo run` so the binary has debug symbols and the log gives more information. Also, preferably paste the output to the comment or link it to a gist.

**Comment by vhakulinen** [comment]
4983c99d0cbd74b800679f6248f68d28b02c7197 adds support for function keys. Regarding shift key, it by itself (afaik) doesn't do anything and  thus' is not sent to neovim.

**Comment by alexlai97** [comment]
> [4983c99](https://github.com/vhakulinen/gnvim/commit/4983c99d0cbd74b800679f6248f68d28b02c7197) adds support for function keys. Regarding shift key, it by itself (afaik) doesn't do anything and thus' is not sent to neovim.

Function key works!

**Comment by alexlai97** [comment]
> Run with `cargo run` so the binary has debug symbols and the log gives more information. Also, preferably paste the output to the comment or link it to a gist.

Here's error output: [https://transfer.sh/A8mlu/err.log](url)

**Comment by vhakulinen** [comment]
Can you try now?

**Comment by alexlai97** [comment]
> Can you try now?

It seems to work fine!

**Comment by badosu** [comment]
Is there any item preventing this issue from being closed?

**Comment by alexlai97** [comment]
> Is there any item preventing this issue from being closed?

For 5. I would like to have an option for toggling to show unfocused info (where the completion is from, snippet ? language client protocol ? or just word from dictionary). Now it is only showing info for the focused entry.

For 6. I am not actively trying to find solution to use [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) with preview option. I believe it is possible to use but it is not that urgent for me. It would be nice to have a plugin for [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) similar to [gnvim-lsp](https://github.com/vhakulinen/gnvim-lsp) though.

**Comment by badosu** [comment]
For 6. I use [coc.vim](https://github.com/neoclide/coc.nvim) and use its preview window with gnvim with no problems (see 'doHover' mapping on the readme)

**Comment by vhakulinen** [comment]
Opened #41 for the 5th point. Closing this one as other issues mentioned here are solved. For the new 6th point, you can look at the gnvim-lsp's source and `:h gnvim-cursor-tooltip` on how to use the cursor tooltip to display other content.

**Comment by NOBLES5E** [comment]
It seems that the issue is still present on latest master branch:

![image](https://user-images.githubusercontent.com/18649508/133827750-c5d0a2e8-44b9-49a5-bfc3-57f46344ded3.png)


The text is `a 窝窝问我,窝窝沃尔沃,我问我欧文`
