### ISSUE TITLE
Font rendering issues with pango 1.44

### ISSUE THREAD

**Issue by last-partizan** [vhakulinen/gnvim#85]
After updating to pango-1.44 command menu is invisible (i'm using `--disable-ext-cmdline`, with gnvim's cmdline it's okay)
![Screenshot from 2019-07-28 22-59-39](https://user-images.githubusercontent.com/301015/62012218-16594e00-b18c-11e9-9172-f9098395d762.png)

After scrolling with mouse scroll fonts become blurred:
![Screenshot from 2019-07-28 22-59-01](https://user-images.githubusercontent.com/301015/62012226-2bce7800-b18c-11e9-83bc-7ddd030c13de.png)

neovim-gtk also has similar problems https://github.com/daa84/neovim-gtk/issues/208 (and there is some details about why: pango deprecated Freetype and using Harfbuzz instead)

**Comment by vhakulinen** [comment]
This is likely a duplicate of #84. I'll close this in favor of that.

**Comment by vhakulinen** [comment]
Reopened this to track progress with the pango 1.44 issue. I miss interpreted #84 to be an issue with pango 1.44, which is not. There is some discussion in that (#84) that are related to this issue here.

**Comment by smolck** [comment]
So, this is interesting. Supposedly, pango is now supposed to continue rounding glyph positions by default, maintaining the pre-1.44 behavior; subpixel positioning is now optional. However, when throwing a `dbg(&self)` after [this line in context.rs](https://github.com/vhakulinen/gnvim/blob/68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc/src/ui/grid/context.rs#L216), I get the following:

Pango 1.43:
```
[src/ui/grid/context.rs:217] &self = CellMetrics {
    height: 26.0,
    width: 10.0,
    ascent: 19.0,
    decent: 7.0,
    underline_thickness: 2.0,
    underline_position: -1.0,
    line_space: 0,
    font: Font {
        name: "Iosevka Extrabold",
        height: 14.0,
    },
}
```

Pango ~1.44.5:
```
[src/ui/grid/context.rs:217] &self = CellMetrics {
    height: 24.5283203125,
    width: 9.0,
    ascent: 18.2373046875,
    decent: 6.291015625,
    underline_thickness: 1.8671875,
    underline_position: -0.93359375,
    line_space: 0,
    font: Font {
        name: "Iosevka Extrabold",
        height: 14.0,
    },
}
```

Unless I'm missing something, it doesn't seem that the glyphs are rounding as they should be, possibly causing some if not all of the problems we're seeing with pango 1.44.

**Comment by smolck** [comment]
@vhakulinen @badosu Okay, so I think we were right about the problem when we thought it was subpixel positioning. For some reason, it doesn't seem that glyph positioning is being rounded, and it's causing the problems we're seeing.

Here's a workaround that we may or may not want to use. It's just `ceil`ing the values, and it seems to fix the problems we've seen for me (no more fuzzy scrolling, weird text placement, etc):
```diff
diff --git a/src/ui/grid/context.rs b/src/ui/grid/context.rs
index 1b0c468..25c3f58 100644
--- a/src/ui/grid/context.rs
+++ b/src/ui/grid/context.rs
@@ -204,15 +204,16 @@ impl CellMetrics {
             .get_metrics(Some(&self.font.as_pango_font()), None)
             .unwrap();
         let extra = self.line_space as f64 / 2.0;
-        self.ascent = fm.get_ascent() as f64 / pango::SCALE as f64 + extra;
-        self.decent = fm.get_descent() as f64 / pango::SCALE as f64 + extra;
-        self.height = self.ascent + self.decent;
+        self.ascent = (fm.get_ascent() as f64 / pango::SCALE as f64 + extra).ceil();
+        self.decent = (fm.get_descent() as f64 / pango::SCALE as f64 + extra).ceil();
+        self.height = (self.ascent + self.decent).ceil();
         self.width = (fm.get_approximate_digit_width() / pango::SCALE) as f64;
 
         self.underline_position =
-            fm.get_underline_position() as f64 / pango::SCALE as f64 - extra;
+            (fm.get_underline_position() as f64 / pango::SCALE as f64 - extra).ceil();
         // TODO(ville): make the underline thickness a bit thicker (one 10th of the cell height?).
         self.underline_thickness =
-            fm.get_underline_thickness() as f64 / pango::SCALE as f64 * 2.0;
+            (fm.get_underline_thickness() as f64 / pango::SCALE as f64 * 2.0).ceil();
     }
 }
```
The output with the above diff isn't quite the same as it was with pango 1.43 though (width is smaller, underline_position is bigger):
```
[src/ui/grid/context.rs:217] &self = CellMetrics {
    height: 26.0,
    width: 9.0,
    ascent: 19.0,
    decent: 7.0,
    underline_thickness: 2.0,
    underline_position: -0.0,
    line_space: 0,
    font: Font {
        name: "Iosevka Extrabold",
        height: 14.0,
    },
}
```
A true fix for all of these seems to be to support subpixel positioning[1] in GNvim, but I don't know how to implement that. If anyone can give me some pointers, I'd be happy to help out. For now, if we want I can keep a fork for those who need a workaround (or we can `ceil` the values in master until we add support for subpixel positioning).

As a side note, I wonder why subpixel positioning isn't off by default? I would think it should be, considering the gnome blog about pango 1.44 says this[2]:
> Font rendering is a sensitive topic; every change here is likely to upset some people (in particular those with carefully tuned font setups).

>We did not help things by enabling subpixel positioning unconditionally in Pango, when it is only supported in cairo master.  When used with the released cairo, this leads to unpleasantly uneven glyph placement.  Even with cairo master, some compositors have not 
been updated to support subpixel positioning (e.g. win32, xcb).

>To address this problem, subpixel positioning is now optional, and off by default. Use
`pango_context_set_round_glyph_positions (context, FALSE)`
to turn it on.

Interestingly, when looking at the docs from gtk-rs for pango, I couldn't find a function like `set_round_glyph_positions` or anything. It may be under a different name; I'm not sure. I may try to use the git version of gtk-rs (and thus pango) to see if that was the problem.

[1]: Is subpixel positioning causing the difference in cell metrics? If not let me know; if subpixel positioning isn't the cause, then it makes more sense that the values for the cell metrics aren't rounded.
[2]: From here: https://blogs.gnome.org/mclasen/2019/08/07/pango-1-44-wrap-up/

**Comment by smolck** [comment]
@last-partizan Could you try out the above diff and see if it fixes this issue for you?

**Comment by smolck** [comment]
Okay, so I was wrong; I thought that `FontMetrics` returned floats, when it returns `i32`'s, so my bad there. 

After realizing `FontMetrics` returned floats, I did some testing and the integer values from the `FontMetrics` functions like `get_ascent()`, `get_descent()`, etc. are different between the two pango versions (thus causing the `CellMetrics` values to be different):

Pango v1.44:
```
[src/ui/grid/context.rs:208] fm.get_ascent() = 18675
[src/ui/grid/context.rs:209] fm.get_descent() = 6442
[src/ui/grid/context.rs:210] fm.get_approximate_digit_width() = 9216
[src/ui/grid/context.rs:211] fm.get_underline_position() = -956
[src/ui/grid/context.rs:212] fm.get_underline_thickness() = 956
[src/ui/grid/context.rs:213] pango::SCALE = 1024
```

Pango v1.43:
```
[src/ui/grid/context.rs:208] fm.get_ascent() = 19456
[src/ui/grid/context.rs:209] fm.get_descent() = 7168
[src/ui/grid/context.rs:210] fm.get_approximate_digit_width() = 10240
[src/ui/grid/context.rs:211] fm.get_underline_position() = -1024
[src/ui/grid/context.rs:212] fm.get_underline_thickness() = 1024
[src/ui/grid/context.rs:213] pango::SCALE = 1024
```

See also: https://github.com/daa84/neovim-gtk/issues/208#issuecomment-529204490

**Comment by last-partizan** [comment]
@smolck Yes, it fixes issue.

Btw, even this patch fixes it:

```.patch
diff --git a/src/ui/grid/context.rs b/src/ui/grid/context.rs
index 1b0c468..a09758a 100644
--- a/src/ui/grid/context.rs
+++ b/src/ui/grid/context.rs
@@ -206,7 +206,7 @@ impl CellMetrics {
         let extra = self.line_space as f64 / 2.0;
         self.ascent = fm.get_ascent() as f64 / pango::SCALE as f64 + extra;
         self.decent = fm.get_descent() as f64 / pango::SCALE as f64 + extra;
-        self.height = self.ascent + self.decent;
+        self.height = (self.ascent + self.decent).ceil();
         self.width = (fm.get_approximate_digit_width() / pango::SCALE) as f64;
 
         self.underline_position =
```

**Comment by last-partizan** [comment]
Initial problem is solved by rounding, but cursor position is starting to drift as you move farther right:

![Screenshot from 2019-09-08 22-07-15](https://user-images.githubusercontent.com/301015/64493164-3e58c880-d285-11e9-86ae-ed6be79e389d.png)
![Screenshot from 2019-09-08 22-07-34](https://user-images.githubusercontent.com/301015/64493163-3e58c880-d285-11e9-9c7a-45821f545f79.png)
![Screenshot from 2019-09-08 22-07-47](https://user-images.githubusercontent.com/301015/64493162-3e58c880-d285-11e9-8683-854d1c4e4990.png)

(invalid cursor position in visual mode)
![Screenshot from 2019-09-08 22-08-10](https://user-images.githubusercontent.com/301015/64493161-3dc03200-d285-11e9-94a0-2bc244faa07a.png)

Like here: https://github.com/daa84/neovim-gtk/issues/208#issuecomment-518198200

**Comment by last-partizan** [comment]
Here is another discussion on this issue: https://github.com/harfbuzz/harfbuzz/issues/1892

**Comment by XanthusL** [comment]
```
 OS: Arch Linux 
 Kernel: x86_64 Linux 4.19.72-1-lts
 Uptime: 10h 31m
 Packages: 1567
 Shell: zsh 5.7.1
 Resolution: 3840x1080
 DE: XFCE4
 WM: Xfwm4
 WM Theme: Paper
 GTK Theme: Paper [GTK2]
 Icon Theme: Paper
 Font: Sans 12
 CPU: Intel Core i7-8750H @ 12x 4.1GHz [51.0°C]
 GPU: GeForce GTX 1050 Ti Mobile
 RAM: 2780MiB / 7821MiB

```
```
pango 1:1.44.6-1
```
![image](https://user-images.githubusercontent.com/16461061/65041098-844e1480-d988-11e9-956d-7a5bb4520062.png)

**Comment by smolck** [comment]
> Initial problem is solved by rounding, but cursor position is starting to drift as you move farther right:

> Here is another discussion on this issue: [harfbuzz/harfbuzz#1892](https://github.com/harfbuzz/harfbuzz/issues/1892)

@last-partizan After reading that thread, it appears to me that our best bet for now is to round the values as you did in https://github.com/vhakulinen/gnvim/issues/85#issuecomment-529230236. The cursor drifting is due to that issue in harfbuzz, right? In which case, that problem is an upstream one. We'll just have to wait for a fix; that is, of course, unless there is a workaround we could implement in GNvim. I'm just not sure how that could be done; any ideas?

**Comment by smolck** [comment]
As an aside, when the lines across the screen appear like in the screenshot in https://github.com/vhakulinen/gnvim/issues/85#issuecomment-532198604, if you press `:` to open the cmdline it appears to "reset" the screen and the lines disappear. Is anyone else getting this behavior?

**Comment by last-partizan** [comment]
Not sure how to fix this exactly, but neovim-gtk somehow fixed their issues (https://github.com/daa84/neovim-gtk/issues/208)

@smolck yes, i was able to reproduce this "reset", but for me it resets not completely, lines just became thinner.

**Comment by last-partizan** [comment]
https://github.com/harfbuzz/harfbuzz/issues/1892#issuecomment-559920035

Looks like harfbuzz has nothing to do with this, it's a pango issue.

**Comment by smolck** [comment]
Okay, so after some further debugging, I've figured out where the "reset" is coming from. It's coming from this line:
https://github.com/vhakulinen/gnvim/blob/65846f45020b338fedd932b058c9e8036dadd976/src/ui/cmdline.rs#L575

If that line is commented out, then the "reset" doesn't happen. @vhakulinen Any ideas why calling `show_all` on a `gtk::Fixed` would cause visual artifacts to disappear?

**Comment by vhakulinen** [comment]
> Any ideas why calling show_all on a gtk::Fixed would cause visual artifacts to disappear?

It probably invalidates what ever is on the screen and causes the whole buffer to be redrawn.

**Comment by vhakulinen** [comment]
Anyone having probmels with pango 1.44, can you try https://github.com/vhakulinen/gnvim/tree/fix-pango144?

**Comment by last-partizan** [comment]
It works fine for me, without artifacts.

Except for this thin lines in statusline
![Screenshot from 2020-01-08 09-50-53](https://user-images.githubusercontent.com/301015/71959892-74d72d80-31fc-11ea-8bf1-1863b66ad122.png)

**Comment by yurakl** [comment]
@vhakulinen  In my configuration with a vertical split, the right status line is truncated on the right side, as if the right margin is incorrectly calculated.

**Comment by cmdln** [comment]
I upgraded to Kubuntu 20.04 yesterday and started seeing this issue. I switched to the fix-pango144 branch and it mostly fixed my issues.
![image](https://user-images.githubusercontent.com/55718/80868987-b4be9680-8c6b-11ea-96cc-638f7afe460f.png)
It looks like the right edge is off in some way. If I resize the window, I can see more of the clipped text but no width consistently seems to line up the window edge with where the line wraps.

My configs are at https://github.com/cmdln/vimrc

**Comment by vhakulinen** [comment]
This is fixed in the master branch.

**Comment by yurakl** [comment]
I still have the same problem with the latest master branch.
Also the character displayed under the cursor is wrong - it's always the next character on the current line.

**Comment by vhakulinen** [comment]
Can you post a screenshot?

**Comment by yurakl** [comment]
Right after changing gui font ":set guifont=Monospace:h11". The status line "auto-corrects" after switching to another window.
pango 1.44.7

![image](https://user-images.githubusercontent.com/62148/85931187-8090dc00-b890-11ea-9eaf-dffc3cef7c74.png)

**Comment by vhakulinen** [comment]
Apparently I did oopsie and managed to slip off-by-one error in there (which doesn't happen with my init.vim). I can reproduce the cursor bug with `-u NORC`.

But the text doesn't look to be blurry?

**Comment by yurakl** [comment]
No, the text is not blurry. Did you click on the image to see it unscaled?

**Comment by vhakulinen** [comment]
Ah, right. The status line overflows on the right side.

Is this on arch linux?

**Comment by cmdln** [comment]
I am also seeing the incorrect character under cursor behavior after building and install from master.
![image](https://user-images.githubusercontent.com/55718/85949537-6228f000-b925-11ea-8830-9a792c96bd59.png)

**Comment by vhakulinen** [comment]
Pushed fix for the cursor thing to master

**Comment by cmdln** [comment]
Can confirm the cursor fix.

**Comment by yurakl** [comment]
> Ah, right. The status line overflows on the right side.
> 
> Is this on arch linux?

Yes.

**Comment by vhakulinen** [comment]
> Right after changing gui font ":set guifont=Monospace:h11". The status line "auto-corrects" after switching to another window.
> pango 1.44.7
> 
> ![image](https://user-images.githubusercontent.com/62148/85931187-8090dc00-b890-11ea-9eaf-dffc3cef7c74.png)

I couldn't reproduce this in fresh arch linux installation.

Can you try with `gnvim -- -u NORC` and see if the status line is still too wide?

**Comment by yurakl** [comment]
Yes, it still happens with bfc76297345ab772cf3e9b88d460822c10e855a2.
